name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create output branch if it doesn't exist
        run: |
          git fetch origin output || git checkout --orphan output
          git checkout -B output

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: bhavishyamaheshwari
          outputs: |
            github-contribution-grid-snake.svg

      - name: Commit Snake
        run: |
          git add github-contribution-grid-snake.svg
          git commit -m "🐍 Update Snake" || echo "No changes to commit"

      - name: Push to Remote
        run: |
          git push --set-upstream origin output --force
