name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create output branch if missing
        run: |
          if git ls-remote --exit-code --heads origin output; then
            git checkout output
          else
            git checkout --orphan output
          fi

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: bhavishyamaheshwari
          outputs: github-contribution-grid-snake.svg

      - name: Commit & Push
        run: |
          git add github-contribution-grid-snake.svg
          git commit -m "🐍 Update Snake" || echo "No changes to commit"
          git push --set-upstream origin output --force
